# Generated by Django 4.2.7 on 2025-06-07 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralrelationship',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='referralsystem',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ReferralTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral_relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.referralrelationship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_transactions', to='users.userprofile')),
            ],
            options={
                'db_table': 'referral_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
