# Generated by Django 4.2.7 on 2025-06-07 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_referralrelationship_amount_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'referral_bonus_levels',
                'ordering': ['level'],
            },
        ),
        migrations.RemoveField(
            model_name='referralrelationship',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='referralsystem',
            name='total_earnings',
        ),
        migrations.RemoveField(
            model_name='referraltransaction',
            name='referral_relationship',
        ),
        migrations.RemoveField(
            model_name='referraltransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='referraltransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referraltransaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referraltransaction',
            name='referred_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_source', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='referraltransaction',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_earnings', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='referraltransaction',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='referraltransaction',
            name='transaction_type',
            field=models.CharField(choices=[('referral', 'Referral Bonus'), ('commission', 'Level Commission')], default='referral', max_length=20),
        ),
    ]
