# Generated by Django 4.2.7 on 2025-06-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_default_referral_bonus_levels'),
        ('users', '0005_bankaccount_wallet_wallettransaction'),
    ]

    operations = [
    ]
