# Generated by Django 4.2.7 on 2025-06-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_bankaccount_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_withdrawal_amount', models.DecimalField(decimal_places=2, default=20, max_digits=10)),
                ('max_withdrawal_amount', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('max_daily_withdrawals', models.IntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Withdrawal Settings',
                'verbose_name_plural': 'Withdrawal Settings',
            },
        ),
    ]
