from django.urls import path, include
from django.shortcuts import redirect
from . import views
from rest_framework.routers import DefaultRouter
from .views import VideoViewSet, VideoPriceViewSet, UserVideoViewSet, WatchListViewSet

router = DefaultRouter()
router.register(r'api/categories', views.CategoryViewSet)
router.register(r'api/live-streams', views.LiveStreamViewSet)
router.register(r'videos', VideoViewSet)
router.register(r'video-prices', VideoPriceViewSet)
router.register(r'user-videos', UserVideoViewSet, basename='user-videos')
router.register(r'watchlist', WatchListViewSet, basename='watchlist')

urlpatterns = [
    path('', views.index_view, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('normal-users/', views.normal_users_view, name='normal_users'),
    path('profile/', views.profile_view, name='profile'),
    path('settings/', views.settings_view, name='settings'),
    path('help-center/', views.help_center_view, name='help_center'),
    path('help-center/submit-bug-report/', views.submit_bug_report_view, name='submit_bug_report'),
    path('help-center/known-issues/', views.known_issues_view, name='known_issues'),
    path('help-center/bug-report/<int:report_id>/', views.bug_report_detail_view, name='bug_report_detail'),
    path('settings/change-password/', views.change_password, name='change_password'),
    path('managers/create/', views.create_manager, name='create_manager'),
    path('managers/manage/', views.manage_users, name='manage_users'),
    path('api/users/<int:user_id>/', views.user_api, name='user_api'),
    path('api/users/<int:user_id>/toggle-status/', views.toggle_user_status, name='toggle_user_status'),
    path('api/users/<int:user_id>/delete/', views.delete_user, name='delete_user'),
    path('api/users/<int:user_id>/details/', views.get_user_details, name='get_user_details'),
    path('managers/delete/<int:user_id>/', views.delete_user_direct, name='delete_user_direct'),
    path('export/excel/', views.export_users_excel, name='export_users_excel'),
    path('export/pdf/', views.export_users_pdf, name='export_users_pdf'),
    path('categories/', views.category_list, name='category_list'),
    path('categories/add/', views.add_category, name='add_category'),
    path('categories/<int:category_id>/edit/', views.edit_category, name='edit_category'),
    path('categories/<int:category_id>/delete/', views.delete_category, name='delete_category'),
    path('categories/<int:category_id>/toggle-status/', views.toggle_category_status, name='toggle_category_status'),
    path('categories/<int:category_id>/toggle-home/', views.toggle_category_home, name='toggle_category_home'),
    path('categories/update-order/', views.update_category_order, name='update_category_order'),
    path('live-streams/add/', views.add_live_stream, name='add_live_stream'),
    path('live-streams/', views.live_stream_list, name='live_stream_list'),
    path('live-streams/<int:live_stream_id>/edit/', views.edit_live_stream, name='edit_live_stream'),
    path('live-streams/<int:live_stream_id>/delete/', views.delete_live_stream, name='delete_live_stream'),
    path('live-streams/<int:live_stream_id>/toggle-status/', views.toggle_live_stream_status, name='toggle_live_stream_status'),
    path('live-streams/update-order/', views.update_live_stream_order, name='update_live_stream_order'),
    path('api/frontend/categories/', views.frontend_categories, name='frontend_categories'),
    path('api/frontend/states/', views.frontend_states, name='frontend_states'),
    path('api/frontend/districts/', views.frontend_districts, name='frontend_districts'),
    path('api/frontend/constituencies/', views.frontend_constituencies, name='frontend_constituencies'),
    path('api/frontend/mandals/', views.frontend_mandals, name='frontend_mandals'),
    path('api/frontend/villages/', views.frontend_villages, name='frontend_villages'),
    path('states/', views.state_list, name='state_list'),
    path('states/add/', views.add_state, name='add_state'),
    path('states/edit/<int:state_id>/', views.edit_state, name='edit_state'),
    path('states/delete/<int:state_id>/', views.delete_state, name='delete_state'),
    path('states/<int:state_id>/toggle-status/', views.toggle_state_status, name='toggle_state_status'),
    path('api/reorder-states/', views.reorder_states, name='reorder_states'),
    path('api/reorder-districts/', views.reorder_districts, name='reorder_districts'),
    path('districts/', views.district_list, name='district_list'),
    path('districts/add/', views.add_district, name='add_district'),
    path('districts/edit/<int:district_id>/', views.edit_district, name='edit_district'),
    path('districts/delete/<int:district_id>/', views.delete_district, name='delete_district'),
    path('districts/<int:district_id>/toggle-status/', views.toggle_district_status, name='toggle_district_status'),
    path('api/districts/by-state/<int:state_id>/', views.get_districts_by_state, name='get_districts_by_state'),
    path('api/constituencies/by-district/<int:district_id>/', views.get_constituencies_by_district, name='get_constituencies_by_district'),
    path('api/mandals/by-constituency/<int:constituency_id>/', views.get_mandals_by_constituency, name='get_mandals_by_constituency'),
    path('constituencies/', views.constituency_list, name='constituency_list'),
    path('constituencies/add/', views.add_constituency, name='add_constituency'),
    path('constituencies/edit/<int:constituency_id>/', views.edit_constituency, name='edit_constituency'),
    path('constituencies/delete/<int:constituency_id>/', views.delete_constituency, name='delete_constituency'),
    path('mandals/', views.mandal_list, name='mandal_list'),
    path('mandals/add/', views.add_mandal, name='add_mandal'),
    path('mandals/edit/<int:mandal_id>/', views.edit_mandal, name='edit_mandal'),
    path('mandals/delete/<int:mandal_id>/', views.delete_mandal, name='delete_mandal'),
    path('toggle-mandal-status/<int:mandal_id>/', views.toggle_mandal_status, name='toggle_mandal_status'),
    path('villages/', views.village_list, name='village_list'),
    path('villages/add/', views.add_village, name='add_village'),
    path('villages/edit/<int:village_id>/', views.edit_village, name='edit_village'),
    path('villages/delete/<int:village_id>/', views.delete_village, name='delete_village'),
    path('villages/toggle-status/<int:village_id>/', views.toggle_village_status, name='toggle_village_status'),
    path('reorder-villages/', views.reorder_villages, name='reorder_villages'),
    path('toggle-constituency-status/<int:constituency_id>/', views.toggle_constituency_status, name='toggle_constituency_status'),
    path('reorder-constituencies/', views.reorder_constituencies, name='reorder_constituencies'),
    path('reorder-mandals/', views.reorder_mandals, name='reorder_mandals'),
    path('api/users/<int:user_id>/referral-tree/', views.get_referral_tree, name='user_referral_tree'),
    path('settings/referral/', views.referral_settings, name='referral_settings'),
    path('settings/referral/update/', views.update_referral_settings, name='update_referral_settings'),
    path('settings/withdrawal-limits/', views.withdrawal_limits, name='withdrawal_limits'),
    path('settings/withdrawal-limits/update/', views.update_withdrawal_limits, name='update_withdrawal_limits'),
    path('withdrawals/', views.withdrawal_management, name='withdrawal_management'),
    path('withdrawals/details/<int:transaction_id>/', views.get_withdrawal_details, name='get_withdrawal_details'),
    path('withdrawals/update-status/', views.update_withdrawal_status, name='update_withdrawal_status'),
    path('videos/', views.video_list, name='video_list'),
    path('videos/add/', views.add_video, name='add_video'),
    path('videos/<int:video_id>/edit/', views.edit_video, name='edit_video'),
    path('videos/<int:video_id>/toggle-status/', views.toggle_video_status, name='toggle_video_status'),
    path('videos/<int:video_id>/delete/', views.delete_video, name='delete_video'),
    path('videos/hero-management/', views.hero_management, name='hero_management'),
    path('videos/<int:video_id>/toggle-hero/', views.toggle_hero_status, name='toggle_hero_status'),
    path('videos/update-hero-order/', views.update_hero_order, name='update_hero_order'),
    path('api/videos/hero/', views.get_hero_videos, name='hero-videos'),
    path('api/', include(router.urls)),
    path('api/videos/category/<int:category_id>/', views.get_videos_by_category, name='get_videos_by_category'),
]