# Generated by Django 4.2.7 on 2025-06-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_accounts', '0003_bankaccount_wallettransaction_withdrawalauditlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='withdrawalauditlog',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='withdrawalauditlog',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='withdrawaldocument',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='withdrawaldocument',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='withdrawaldocument',
            name='verified_by',
        ),
        migrations.DeleteModel(
            name='WithdrawalLimit',
        ),
        migrations.RemoveField(
            model_name='withdrawalriskassessment',
            name='assessed_by',
        ),
        migrations.RemoveField(
            model_name='withdrawalriskassessment',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='withdrawalverificationqueue',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='withdrawalverificationqueue',
            name='transaction',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Category image', null=True, upload_to='categories/'),
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
        migrations.DeleteModel(
            name='WithdrawalAuditLog',
        ),
        migrations.DeleteModel(
            name='WithdrawalDocument',
        ),
        migrations.DeleteModel(
            name='WithdrawalRiskAssessment',
        ),
        migrations.DeleteModel(
            name='WithdrawalVerificationQueue',
        ),
    ]
