# Generated by Django 4.2.7 on 2025-06-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_accounts', '0006_video_videoprice_uservideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_url',
            field=models.URLField(blank=True, help_text='URL to master HLS playlist', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Whether video has been converted to HLS'),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
