# Generated by Django 4.2.7 on 2025-06-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_accounts', '0007_video_hls_url_video_is_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='progress_percent',
            field=models.FloatField(default=0, help_text='Progress percentage of video processing'),
        ),
    ]
