# Generated by Django 4.2.7 on 2025-06-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_accounts', '0011_rename_error_message_video_processing_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_promo_processed',
            field=models.BooleanField(default=False, help_text='Whether promo video has been converted to HLS'),
        ),
        migrations.AddField(
            model_name='video',
            name='portrait_thumbnail',
            field=models.ImageField(blank=True, help_text='Portrait thumbnail (9:16 ratio) for mobile view', null=True, upload_to='videos/portrait_thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='promo_hls_url',
            field=models.URLField(blank=True, help_text='URL to master HLS playlist for promo video', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='promo_processing_error',
            field=models.TextField(blank=True, help_text='Error message if promo video processing failed', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='promo_processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Processing status of promo video', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='promo_progress_percent',
            field=models.FloatField(default=0, help_text='Progress percentage of promo video processing'),
        ),
        migrations.AddField(
            model_name='video',
            name='promo_video',
            field=models.FileField(blank=True, help_text='Short promotional video clip', null=True, upload_to='videos/promos/'),
        ),
    ]
