# Generated by Django 4.2.7 on 2025-06-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_accounts', '0012_video_is_promo_processed_video_portrait_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='promo_image',
            field=models.ImageField(blank=True, help_text='Promotional image for the video', null=True, upload_to='videos/promo_images/'),
        ),
    ]
