# Generated by Django 4.2.7 on 2025-06-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_accounts', '0014_cast_remove_video_promo_image_videocast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-hero_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='video',
            name='hero_order',
            field=models.IntegerField(default=0, help_text='Order in which to display hero videos (0 = last)'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_hero',
            field=models.BooleanField(default=False, help_text='Select to display this video in hero section'),
        ),
    ]
